os:
- linux
- osx
- windows
language: c
addons:
  homebrew:
    packages:
    - pbzip2
    - md5sha1sum
    update: true
  apt:
    packages:
    - pbzip2
    - realpath
script:
- ./make-release.sh
- cd test
- "./datetest"
- "./extracttest"
- "./suidtest"
- "./tarextratest"
- "./appendtest"
- "./whitespacetest"
- "./whitespacelicense"
- cd ..
deploy:
  provider: releases
  api_key:
    secure: buH5+nxvAzWcQyC59bIXTNUrV8As07sk7zIz5giHYHoUpTxmoKQBMIAL2Yo7e4uShVM1dy/qFR2unh2vSw6Kt2Kwr17h1osO8/ZORIhFOm7qPJ5UsDQoF/lTbu2EOFtuq3UeJ1KSSVDhpDkFs2P2/nn/Jj0TNSOZ/+4/ZLYEHrI=
  file_glob: true
  file: makeself-*.run
  skip_cleanup: true
  on:
    repo: megastep/makeself
    tags: true
